// Camper comparison: all the content lives here, in plain text, so it can be
// edited by hand. Scores and weights people enter are stored in Supabase.
//
// A fact starting "TBC" is shown as "to confirm".
// w      = default importance: 1 nice to have, 2 important, 3 essential.
// claude = Claude's suggested score for [Hilux, Hotomobil, Goatfell], 0-3,
//          from the facts as known on 2026-09-30. null = cannot score yet.

window.SETUPS = [
  { id: "H",  short: "Hilux",     name: "eBay Hilux",                   sub: "2018 Hilux Invincible X, 99k, camper built on", price: 55000 },
  { id: "RH", short: "Hotomobil", name: "Ranger + Hotomobil Expedition+", sub: "2018 Ranger 2.2 manual, 60k + ex-demo Gladiator SE", price: 53300 },
  { id: "RG", short: "Goatfell",  name: "Ranger + Goatfell LUX Extended", sub: "Same Ranger + new LUX Extended, fully specced", price: 48700 },
];

window.DEALBREAKERS = [
  { name: "Legal payload with four of us, water and kit",
    facts: {
      H:  "Seller says 3.1t actual, 3.25t legal, 'can be uprated to 3.5t quite easily'. Read sensibly: about 150kg of payload today, about 400kg if uprated. Tight for four people, 100L of water and kit. The Pedders +500kg suspension does not change the legal weight. Weighbridge ticket and V5C needed.",
      RH: "TBC. Camper 625kg (Wild Camper) or 790kg (Hotomobil). Plus about 300kg of people and 150kg of water and kit: over a 1 tonne payload unless up-plated.",
      RG: "TBC. Camper about 650kg dry. Same problem as the Hotomobil: needs an up-plate.",
    } },
  { name: "Under 3.5 tonnes (car licence)",
    facts: { H: "Yes at 3.25t as it stands. Seller says it can be uprated to 3.5t (a car licence covers up to 3.5t); needs certifying.", RH: "Yes, if up-plated no higher than 3.5t.", RG: "Yes, if up-plated no higher than 3.5t." } },
  { name: "Sleeps four (girls in our own tent)",
    facts: { H: "Yes. Sleeps 2 adults and a child inside, plus the tent.", RH: "Yes. 2 inside, plus the tent.", RG: "Yes. 2 adults and 2 children inside, or use the tent." } },
];

window.SECTIONS = [
{ id: "truck", name: "The truck", items: [
  { id: "rel", name: "Reliability reputation", w: 3, hint: "3 = known to go forever",
    facts: { H: "Toyota Hilux: the benchmark. Known faults on this engine: DPF clogging, injectors.", RH: "Ford Ranger 2.2: patchier. Oil pump failure is the known killer; Andrew says it has been changed.", RG: "Same Ranger." },
    claude: [3, 2, 2] },
  { id: "miles", name: "Mileage and condition", w: 2, hint: "3 = low miles, full history",
    facts: { H: "99k. Full service. Seller says everything as new.", RH: "60k. Great history per Andrew. Lanoguarded yearly.", RG: "Same Ranger, 60k." },
    claude: [2, 3, 3] },
  { id: "gearbox", name: "Gearbox (automatic preferred)", w: 2, hint: "3 = automatic",
    facts: { H: "Automatic.", RH: "Manual.", RG: "Manual." },
    claude: [3, 1, 1] },
  { id: "power", name: "Engine and pulling power", w: 1, hint: "3 = easy with the camper on",
    facts: { H: "2.4 D-4D, factory about 148bhp, remapped to 180bhp by Elite Tuning, Sheffield (declare to insurer; strains DPF and clutch).", RH: "2.2 TDCi, about 160PS, 'a bit of tuning'.", RG: "Same Ranger." },
    claude: [3, 2, 2] },
  { id: "comfort", name: "Comfort on long drives", w: 3, hint: "3 = happy doing 500 miles a day",
    facts: { H: "Invincible X: leather heated seats, touchscreen nav, reversing camera. Firm Hilux ride.", RH: "TBC trim level. Rangers ride better than Hiluxes.", RG: "Same Ranger." },
    claude: [2, 2, 2] },
  { id: "offroad", name: "Off-road ability", w: 1, hint: "3 = more than we'll ever need",
    facts: { H: "Locking diffs, high/low range, winch bumper, underguard, sliders, uprated suspension.", RH: "4x4 with low range. TBC diff lock. Uprated rear leaf springs, better tyres.", RG: "Same Ranger." },
    claude: [3, 2, 2] },
  { id: "city", name: "City driving and parking", w: 2, hint: "3 = no worse than a big car",
    facts: { H: "Alcove body over the cab: TBC overall height.", RH: "Tall fixed hard body. Tailgate down.", RG: "Pop-up, lowest when closed. Tailgate down, 300-400mm overhang." },
    claude: [1, 1, 2] },
  { id: "theft", name: "Theft risk and security", w: 2, hint: "3 = low risk, well protected",
    facts: { H: "Hilux is the UK's most stolen pickup. Has a Ghost immobiliser.", RH: "Ranger far less targeted. Thatcham S5+ tracker.", RG: "Same Ranger." },
    claude: [1, 3, 3] },
  { id: "parts", name: "Parts and garages abroad", w: 2, hint: "3 = fixable anywhere",
    facts: { H: "Toyota dealers almost everywhere, including Turkey, Morocco, Georgia.", RH: "Ford is common in all of those too.", RG: "Same Ranger." },
    claude: [3, 2, 2] },
  { id: "fuel", name: "Fuel economy", w: 1, hint: "3 = cheapest to run",
    facts: { H: "Seller says good. Heavy build and roof lights.", RH: "TBC. Tall hard body, more drag.", RG: "TBC. Lower pop-up, less drag." },
    claude: [2, 1, 2] },
]},
{ id: "weight", name: "Weight and size", items: [
  { id: "payload", name: "Payload margin when loaded", w: 3, hint: "3 = comfortable margin",
    facts: { H: "About 150kg legal payload today, about 400kg if uprated to 3.5t (from the seller's 3.1t / 3.25t / 3.5t answer). Four people alone are about 300kg.", RH: "TBC. 625kg or 790kg: likely over without an up-plate.", RG: "TBC. About 650kg: likely over without an up-plate." },
    claude: [1, 0, 1] },
  { id: "overhang", name: "Overhang past the back", w: 1, hint: "3 = little or none",
    facts: { H: "TBC.", RH: "Tailgate down. Floor 186cm.", RG: "300-400mm past the bed (legal limit 1,000mm)." },
    claude: [null, 2, 2] },
  { id: "height", name: "Height: ferries, tolls, car parks", w: 2, hint: "3 = lowest class",
    facts: { H: "Tall even with the roof down (photos). Overall height TBC.", RH: "TBC. Fixed-height body, 195cm inside: tall.", RG: "TBC. Pop-up, low when closed." },
    claude: [1, 1, 2] },
  { id: "work", name: "Truck work needed before use", w: 2, hint: "3 = none",
    facts: { H: "Uprating to 3.5t to be certified. The seller would buy and fit a winch for the asking price.", RH: "Chassis eye bolts, maybe air bag suspension, up-plate the V5. Andrew would organise.", RG: "Mounting, suspension and up-plate likely. TBC who does it." },
    claude: [2, 1, 1] },
]},
{ id: "sleep", name: "Sleeping", items: [
  { id: "bed", name: "Main bed size and comfort", w: 3, hint: "3 = big and comfy",
    facts: { H: "1.4m x 1.9m UK double, with a raised pod for legroom. Alcantara walls, MaxxFan and lights over the bed. Check the length on a tall person: try it.", RH: "Fixed super-king.", RG: "Telescopic king-length." },
    claude: [1, 3, 3] },
  { id: "access", name: "Getting in and out at night", w: 2, hint: "3 = no climbing over anyone",
    facts: { H: "TBC. Alcove over the cab: climb up.", RH: "TBC. Fixed bed, check the climb.", RG: "TBC." },
    claude: [null, null, null] },
  { id: "second", name: "Second bed inside (girls on a wet night)", w: 2, hint: "3 = a proper second bed",
    facts: { H: "Room for a child, per the seller.", RH: "TBC. Does the dinette make a bed?", RG: "Double-length secondary bed (panel folds down)." },
    claude: [2, null, 3] },
  { id: "madeup", name: "Bed stays made up", w: 1, hint: "3 = always ready",
    facts: { H: "Yes, alcove bed.", RH: "Yes, fixed bed.", RG: "TBC. Telescopic bed." },
    claude: [3, 3, 2] },
  { id: "roofdown", name: "Sleep with the roof down (cold, stealth)", w: 2, hint: "3 = yes",
    facts: { H: "Probably, the bed is in the hard alcove. TBC.", RH: "Yes, fixed hard body, nothing to raise.", RG: "TBC. Canvas pop-up." },
    claude: [2, 3, 1] },
]},
{ id: "living", name: "Living inside", items: [
  { id: "headroom", name: "Standing headroom", w: 2, hint: "3 = both of us stand up",
    facts: { H: "TBC. Electric elevating roof.", RH: "195cm (brochure says 6'2\"). Always there.", RG: "Up to about 215cm with the roof up." },
    claude: [null, 3, 3] },
  { id: "table", name: "Internal table", w: 2, hint: "3 = proper table for meals",
    facts: { H: "None seen in the 24 photos. Has an Alu-Cab table for outside.", RH: "Yes, dinette with table (in the photos).", RG: "TBC." },
    claude: [0, 3, null] },
  { id: "seats", name: "Seats for four inside on a wet day", w: 2, hint: "3 = four sit comfortably",
    facts: { H: "Bench sofa along the back; the photos suggest two or three seats.", RH: "Dinette, two benches facing.", RG: "Sofa area. TBC for four." },
    claude: [1, 2, 1] },
  { id: "storage", name: "Storage inside", w: 2, hint: "3 = room for four months",
    facts: { H: "Overhead cupboards all round, storage under the sofa.", RH: "TBC.", RG: "Push-out side expansion for fridge, microwave and storage." },
    claude: [3, null, 2] },
  { id: "hanging", name: "Hanging space for coats", w: 1, hint: "3 = a wardrobe",
    facts: { H: "A tall wardrobe-style cupboard is visible in the photos.", RH: "TBC.", RG: "TBC." }, claude: [2, null, null] },
  { id: "light", name: "Windows, light and views", w: 1, hint: "3 = bright with views",
    facts: { H: "Flush dual-pane windows with fly nets and blinds.", RH: "Two 45x50 living windows, one 70x30 kitchen window. Skylight optional.", RG: "7 windows: skylight, 4 upper, 2 lower." },
    claude: [2, 1, 3] },
  { id: "vent", name: "Ventilation", w: 2, hint: "3 = no condensation, cool at night",
    facts: { H: "MaxxFan over the bed, Sirocco fan, extractor fans.", RH: "Bathroom hatch with fan. TBC roof fan.", RG: "MaxxFan Deluxe with remote." },
    claude: [3, 1, 3] },
  { id: "insul", name: "Insulation and warmth", w: 3, hint: "3 = snug in snow",
    facts: { H: "RTM hard panels, welded aluminium frame. Canvas on the elevating roof.", RH: "Hard monoblock body, 20mm insulation.", RG: "Aluminium body, multi-layer canvas pop-up." },
    claude: [2, 3, 1] },
  { id: "noise", name: "Quiet in wind and rain", w: 1, hint: "3 = hard walls, quiet",
    facts: { H: "Mostly hard, canvas on the roof section.", RH: "Fully hard body.", RG: "Canvas sides when up." },
    claude: [2, 3, 1] },
]},
{ id: "kitchen", name: "Kitchen", items: [
  { id: "cookin", name: "Indoor cooking", w: 2, hint: "3 = cook a proper meal inside",
    facts: { H: "Single Thetford Autospark gas burner (photo), 400mm deep sink with folding tap, black worktop.", RH: "Double gas hob and sink.", RG: "2,000W induction hob, sink, 20L microwave." },
    claude: [1, 2, 3] },
  { id: "cookout", name: "Outdoor cooking", w: 3, hint: "3 = cooking outside is easy and set up",
    facts: { H: "Outdoor gas BBQ point, fold-down side table, Cadac Safari Chef 2, Alu-Cab table.", RH: "Nothing built in. Portable stove.", RG: "Nothing built in. Portable stove." },
    claude: [3, 1, 1] },
  { id: "fridge", name: "Fridge and freezer", w: 2, hint: "3 = a week's food and a freezer",
    facts: { H: "Alpicool 85L fridge/freezer per the advert (photos show an upright fridge; model to confirm).", RH: "Indel B 90L fridge in the configurator (SE); Wild Camper say it is much bigger than the Expedition's. To confirm on the ex-demo.", RG: "40L compressor fridge on a pull-out slide." },
    claude: [3, 3, 1] },
  { id: "water", name: "Fresh and grey water", w: 2, hint: "3 = several days for four",
    facts: { H: "100L underslung fresh, inline filter. TBC grey.", RH: "55L fresh, 30L grey.", RG: "70L stainless fresh. TBC grey." },
    claude: [3, 1, 2] },
  { id: "gas", name: "Gas supply abroad", w: 1, hint: "3 = refill anywhere",
    facts: { H: "Underslung refillable LPG tank, gauge, leak detector.", RH: "TBC. Bottles?", RG: "No gas needed: induction and diesel." },
    claude: [3, null, 3] },
]},
{ id: "bath", name: "Bathroom", items: [
  { id: "toilet", name: "Toilet", w: 3, hint: "3 = private, flushing, no night walks",
    facts: { H: "Separate toilet room, Thetford swivel toilet with electric flush, heated outlet.", RH: "Thetford C223 cassette toilet in the bathroom.", RG: "Portaloo stored inside. Full-time toilet upgrade available." },
    claude: [3, 3, 1] },
  { id: "showerin", name: "Indoor shower", w: 2, hint: "3 = yes, with hot water",
    facts: { H: "Advert: outdoor shower point only. The seller's email says a shower head is fitted and mentions a shower cubicle; photo 15 shows a toilet room with a pipe at one side. To confirm.", RH: "Yes, in the bathroom.", RG: "No." },
    claude: [null, 3, 0] },
  { id: "showerout", name: "Outdoor shower", w: 1, hint: "3 = hot, with privacy",
    facts: { H: "Outdoor shower point with Alu-Cab shower cube.", RH: "Reich outdoor shower. Curtain £350 on new builds.", RG: "External hot shower with privacy curtain." },
    claude: [3, 2, 3] },
  { id: "hotwater", name: "Hot water off grid", w: 2, hint: "3 = hot water anywhere, any time",
    facts: { H: "Truma Combi D 4 E: diesel heating and hot water, piped to the sink (and the shower, per the seller).", RH: "Truma Therme runs on 230V. The Efficient Energy Package (€420 new) lets it run from the inverter. TBC what the ex-demo has.", RG: "Hot water sink. TBC how it's heated." },
    claude: [3, 1, null] },
]},
{ id: "power", name: "Power", items: [
  { id: "battery", name: "Battery size", w: 3, hint: "3 = days without driving",
    facts: { H: "Fogstar 300Ah lithium (about 3.8kWh), Victron monitoring.", RH: "100Ah lithium (about 1.3kWh).", RG: "400Ah lithium (5kWh)." },
    claude: [3, 1, 3] },
  { id: "solar", name: "Solar", w: 2, hint: "3 = self-sufficient in summer",
    facts: { H: "600W.", RH: "205W.", RG: "400W." },
    claude: [3, 1, 2] },
  { id: "b2b", name: "Charging while driving", w: 2, hint: "3 = fast charging on the move",
    facts: { H: "Victron 50A B2B charger.", RH: "Via the tow bar socket. TBC rate; Andrew's electrician can fit B2B.", RG: "Lithium charger, charges while driving." },
    claude: [3, 1, 2] },
  { id: "inverter", name: "Inverter (240V: kettle, hairdryer)", w: 1, hint: "3 = runs a kettle",
    facts: { H: "Renogy 3,000W.", RH: "Linetech 1,000W. Not a kettle.", RG: "3.6kW." },
    claude: [3, 1, 3] },
  { id: "hookup", name: "Mains hook-up", w: 1, hint: "3 = yes, with charger",
    facts: { H: "240V shore power, 30A charger, consumer unit.", RH: "230V external input.", RG: "CEE hook-up kit." },
    claude: [3, 2, 2] },
  { id: "offsummer", name: "Days off grid in summer", w: 2, hint: "3 = a week or more",
    facts: { H: "Likely a week or more.", RH: "Two or three days, longer if the sun keeps up.", RG: "Likely a week or more." },
    claude: [3, 1, 3] },
  { id: "offwinter", name: "Days off grid in winter", w: 2, hint: "3 = several days",
    facts: { H: "Three or four days with the heater on.", RH: "One or two days. Relies on driving.", RG: "Four or five days." },
    claude: [2, 0, 3] },
  { id: "cold", name: "Battery charging below freezing", w: 1, hint: "3 = self-heating battery",
    facts: { H: "TBC.", RH: "TBC.", RG: "Battery works to about -25C. TBC charging." },
    claude: [null, null, null] },
]},
{ id: "climate", name: "Heating and cooling", items: [
  { id: "heat", name: "Heating", w: 3, hint: "3 = warm in snow",
    facts: { H: "Truma Combi D 4 E diesel, iNet control.", RH: "Eberspächer D2L diesel air heater.", RG: "2.6kW diesel heater, digital thermostat." },
    claude: [3, 2, 2] },
  { id: "frost", name: "Frost protection for the water", w: 2, hint: "3 = tanks and pipes safe in a freeze",
    facts: { H: "Tank is underslung, outside: at risk in a freeze. TBC.", RH: "Truma Therme with frost control. TBC tanks.", RG: "TBC. Not answered by Goatfell." },
    claude: [1, 2, null] },
  { id: "cool", name: "Keeping cool in summer", w: 2, hint: "3 = comfortable in 35C",
    facts: { H: "MaxxFan and Sirocco fan.", RH: "Windows and fan. Air con extra on new builds only.", RG: "7 windows, MaxxFan. Air con option." },
    claude: [2, 1, 2] },
]},
{ id: "outdoor", name: "Outdoor living", items: [
  { id: "awning", name: "Awning", w: 2, hint: "3 = big, quality, quick",
    facts: { H: "Bush Company 270° with lights: top quality.", RH: "Hotomobil 220 x 240cm awning in the configurator; self-supporting upgrade £880 on new builds.", RG: "3.2m side awning, or 270° hard-case (in the £26k + VAT spec)." },
    claude: [3, 2, 3] },
  { id: "extstore", name: "Outside storage (chairs, tent)", w: 2, hint: "3 = the tent and chairs fit easily",
    facts: { H: "Bed lockers, pull-out drawer, large rear box, roof tray, spare wheel carrier.", RH: "Roof rack (Thule style). TBC lockers.", RG: "Exterior racking for shovels and boards; roof rack over the cab possible." },
    claude: [3, 1, 2] },
  { id: "extlight", name: "Outside lighting", w: 1, hint: "3 = light the whole camp",
    facts: { H: "Lots: roof spots, bonnet lights, awning lights, reverse lights.", RH: "2 external lights.", RG: "LED suite; front floodlight option." },
    claude: [3, 1, 2] },
]},
{ id: "practical", name: "Practicalities", items: [
  { id: "setup", name: "Set-up time on arrival", w: 2, hint: "3 = park and it's ready",
    facts: { H: "Electric elevating roof.", RH: "Nothing to raise: hard body.", RG: "Electric pop-up." },
    claude: [2, 3, 2] },
  { id: "demount", name: "Truck usable without the camper", w: 1, hint: "3 = lifts off easily",
    facts: { H: "TBC. Built onto a custom bed: probably not removable.", RH: "Demountable on legs.", RG: "Demountable on legs." },
    claude: [0, 3, 3] },
  { id: "fix", name: "Fixing things abroad", w: 2, hint: "3 = standard parts",
    facts: { H: "Victron, Truma, Thetford: parts everywhere in Europe.", RH: "Built in Turkey. Truma and Thetford parts.", RG: "Bespoke, built abroad. Parts from Goatfell." },
    claude: [3, 2, 1] },
  { id: "support", name: "Warranty and seller support", w: 2, hint: "3 = a proper warranty and help",
    facts: { H: "TBC. The seller is Alpine Overland, a business, so a warranty or consumer-rights cover may apply. Ask.", RH: "UK dealer. TBC warranty.", RG: "1 year body, 1 year everything else." },
    claude: [null, null, 2] },
  { id: "risk", name: "Company or seller risk", w: 2, hint: "3 = no risk to our money",
    facts: { H: "Pay on collection. Check it's not stolen or on finance (HPI).", RH: "Buy stock from a UK dealer.", RG: "Very small company; 80% paid before delivery." },
    claude: [2, 3, 1] },
  { id: "when", name: "How soon we could have it", w: 1, hint: "3 = now",
    facts: { H: "Now, if still for sale.", RH: "Now (ex-demo, built).", RG: "About 4 months from sign-off." },
    claude: [3, 3, 1] },
]},
{ id: "viewing", name: "Seeing it and buying it", items: [
  { id: "distance", name: "Distance from Cornwall", w: 2, hint: "3 = an easy day trip",
    facts: { H: "Mansfield, Notts: about 5 hours each way. Could fit a Manchester trip.", RH: "Bradford on Avon, Wiltshire: about 3 hours. Visit proposed for Sun 15 Nov.", RG: "Dumfries, Scotland: about 7 to 8 hours each way." },
    claude: [1, 3, 0] },
  { id: "visits", name: "Trips needed to view, buy and collect", w: 3, hint: "3 = one trip",
    facts: { H: "One: view, test drive, pay and drive home.", RH: "One or two: view, then collect once the Ranger is prepared and up-plated.", RG: "Two or three: see a unit and measure the truck, then delivery and fitting (4-month build between)." },
    claude: [3, 2, 0] },
  { id: "try", name: "Try before we commit", w: 2, hint: "3 = sleep in it first",
    facts: { H: "Look round and test drive only.", RH: "View the ex-demo; Wild Camper hire Hotomobils from Scotland at £160/day.", RG: "Only a loan of the unit after we've bought the truck." },
    claude: [1, 2, 1] },
  { id: "aftersales", name: "Getting back for fixes", w: 2, hint: "3 = dealer within easy reach",
    facts: { H: "Private sale: any garage or converter.", RH: "Dealer in Wiltshire, reachable in a day.", RG: "Back to Dumfries." },
    claude: [1, 3, 0] },
]},
{ id: "money", name: "Money", items: [
  { id: "price", name: "Purchase price", w: 3, hint: "3 = cheapest",
    facts: { H: "£55,000. The builder's near-identical advert was seen elsewhere at about £65,000.", RH: "£53,300 (£17,500 truck + £35,800 camper).", RG: "About £48,700 (truck + about £31,200 camper incl VAT)." },
    claude: [1, 2, 3] },
  { id: "extra", name: "Extra spend to reach our spec", w: 2, hint: "3 = nothing to add",
    facts: { H: "Little: fully kitted. Winch to be fitted by the seller; uprating to be certified.", RH: "Electrics upgrade £1,000-1,500, up-plate and suspension TBC.", RG: "Up-plate and suspension TBC." },
    claude: [3, 1, 2] },
  { id: "running", name: "Insurance and running costs", w: 2, hint: "3 = cheapest to insure",
    facts: { H: "High: most stolen, remap to declare.", RH: "Lower theft risk. Declare the tuning.", RG: "Same Ranger." },
    claude: [1, 2, 2] },
  { id: "resale", name: "Resale value", w: 2, hint: "3 = holds value",
    facts: { H: "Hiluxes hold value; buyers wary of heavy custom builds.", RH: "Truck and camper sell separately.", RG: "Sell separately; small brand." },
    claude: [2, 2, 2] },
  { id: "hire", name: "Hire income potential", w: 1, hint: "3 = easy to hire out",
    facts: { H: "DIY only.", RH: "Andrew's scheme: £160/day, April-Sept, 20% commission, Makerstudy insurance.", RG: "DIY only." },
    claude: [1, 3, 1] },
]},
{ id: "plans", name: "Fit for our plans", items: [
  { id: "four", name: "Works for four now", w: 3, hint: "3 = easy for four",
    facts: { H: "2 adults and a child inside; girls in the tent.", RH: "2 inside; girls in the tent.", RG: "2 adults and 2 children inside, or tent." },
    claude: [2, 2, 3] },
  { id: "two", name: "Works for two later", w: 3, hint: "3 = perfect for two",
    facts: { H: "Yes, roomy for two with a toilet room.", RH: "Yes, bathroom with shower.", RG: "Yes." },
    claude: [3, 3, 2] },
  { id: "scandi", name: "Scandinavia in winter", w: 2, hint: "3 = made for it",
    facts: { H: "Great heating and battery; underslung water and canvas roof are the risks.", RH: "Hard insulated body and shower; small battery.", RG: "Big battery; canvas pop-up and frost unanswered." },
    claude: [2, 2, 1] },
  { id: "turkey", name: "Turkey in summer", w: 2, hint: "3 = cool and self-sufficient",
    facts: { H: "Fans, big solar, big water, outdoor kitchen.", RH: "Fewer windows, small solar.", RG: "7 windows, MaxxFan, big battery." },
    claude: [3, 1, 3] },
  { id: "long", name: "Four-month trips", w: 3, hint: "3 = comfortable for months",
    facts: { H: "Built by people who've travelled Europe in it.", RH: "Comfortable body; small power and water.", RG: "Good power; small fridge, no shower." },
    claude: [3, 2, 2] },
]},
];
